// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZqc7j9pIW9XdOE9fTGXkXjJRf-phQUOo',
    appId: '1:173594859872:web:2de0c351717225d00f6605',
    messagingSenderId: '173594859872',
    projectId: 'restaurant-app-f7102',
    authDomain: 'restaurant-app-f7102.firebaseapp.com',
    storageBucket: 'restaurant-app-f7102.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_qTGUr1QAb3-Aa0hfXa1l7Zs8dQkYuN0',
    appId: '1:173594859872:android:64cb1ff843eed0430f6605',
    messagingSenderId: '173594859872',
    projectId: 'restaurant-app-f7102',
    storageBucket: 'restaurant-app-f7102.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASpPHNl5wY5yS9hUNLVdDLdz0XvyU91wA',
    appId: '1:173594859872:ios:223738ec11c428cc0f6605',
    messagingSenderId: '173594859872',
    projectId: 'restaurant-app-f7102',
    storageBucket: 'restaurant-app-f7102.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASpPHNl5wY5yS9hUNLVdDLdz0XvyU91wA',
    appId: '1:173594859872:ios:223738ec11c428cc0f6605',
    messagingSenderId: '173594859872',
    projectId: 'restaurant-app-f7102',
    storageBucket: 'restaurant-app-f7102.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZqc7j9pIW9XdOE9fTGXkXjJRf-phQUOo',
    appId: '1:173594859872:web:e276bc5c7df71bc10f6605',
    messagingSenderId: '173594859872',
    projectId: 'restaurant-app-f7102',
    authDomain: 'restaurant-app-f7102.firebaseapp.com',
    storageBucket: 'restaurant-app-f7102.firebasestorage.app',
  );
}
